In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

from sklearn.metrics import confusion_matrix , classification_report , accuracy_score

In [6]:
df1 = pd.read_csv('Final_Data.csv')
df1

Full_Name  organisation_key  person_learner_key  gender_key  \
0         Aadam Ali                 2                2531           1   
1         Aadam Ali                 2                2531           1   
2         Aadam Ali                 2                2531           1   
3         Aadam Ali                 2                2531           1   
4         Aadam Ali                 2                2531           1   
...             ...               ...                 ...         ...   
10603  Zoya Hussain                 1                1246           2   
10604   Zoya Rahman                 4                4469           2   
10605   Zoya Rahman                 4                4469           2   
10606   Zoya Waseem                 5                4482           2   
10607   Zoya Waseem                 5                4482           2   

       IsGifted  Present Gender_Code Student_Status  Behaviour_Points  \
0           NaN        0           M        On Roll               0.0   
1           NaN        0           M        On Roll               0.0   
2           NaN        1           M        On Roll               1.0   
3           NaN        0           M        On Roll               1.0   
4           NaN        1           M        On Roll               2.0   
...         ...      ...         ...            ...               ...   
10603       NaN        1           F        On Roll               NaN   
10604       NaN        0           F        On Roll               1.0   
10605       NaN        1           F        On Roll               1.0   
10606       NaN        1           F        On Roll               NaN   
10607       NaN        0           F        On Roll               NaN   

      IsBankHoliday IsCompanyHoliday IsFederalHoliday IsLastDayOfMonth  \
0                 Y                Y                Y                N   
1                 Y                Y                Y                Y   
2                 N                N                N                N   
3                 N                N                N                Y   
4                 N                N                N                N   
...             ...              ...              ...              ...   
10603             N                N                N                Y   
10604             Y                Y                Y                N   
10605             N                N                N                Y   
10606             N                N                N                N   
10607             N                N                N                Y   

      IsWeekday IsWeekend IsWorkday  MonthNumberOfYear DSEN_Provision_Code  
0             Y         N         N                  7                   K  
1             Y         N         N                  7                   K  
2             Y         N         Y                  7                   K  
3             Y         N         Y                  7                   K  
4             Y         N         Y                  7                   K  
...         ...       ...       ...                ...                 ...  
10603         N         Y         N                  7                 NaN  
10604         Y         N         N                  7                   N  
10605         Y         N         Y                  7                   N  
10606         Y         N         Y                  7                 NaN  
10607         Y         N         Y                  7                 NaN  

[10608 rows x 18 columns]

In [7]:
df1.columns

Index(['Full_Name', 'organisation_key', 'person_learner_key', 'gender_key',
       'IsGifted', 'Present', 'Gender_Code', 'Student_Status',
       'Behaviour_Points', 'IsBankHoliday', 'IsCompanyHoliday',
       'IsFederalHoliday', 'IsLastDayOfMonth', 'IsWeekday', 'IsWeekend',
       'IsWorkday', 'MonthNumberOfYear', 'DSEN_Provision_Code'],
      dtype='object')

In [8]:
df1.dtypes

Full_Name               object
organisation_key         int64
person_learner_key       int64
gender_key               int64
IsGifted               float64
Present                  int64
Gender_Code             object
Student_Status          object
Behaviour_Points       float64
IsBankHoliday           object
IsCompanyHoliday        object
IsFederalHoliday        object
IsLastDayOfMonth        object
IsWeekday               object
IsWeekend               object
IsWorkday               object
MonthNumberOfYear        int64
DSEN_Provision_Code     object
dtype: object

In [9]:
df1.isnull().sum()/100

Full_Name               0.00
organisation_key        0.00
person_learner_key      0.00
gender_key              0.00
IsGifted               93.94
Present                 0.00
Gender_Code             0.00
Student_Status          0.00
Behaviour_Points       27.00
IsBankHoliday           0.00
IsCompanyHoliday        0.00
IsFederalHoliday        0.00
IsLastDayOfMonth        0.00
IsWeekday               0.00
IsWeekend               0.00
IsWorkday               0.00
MonthNumberOfYear       0.00
DSEN_Provision_Code    63.12
dtype: float64

In [10]:
df2 = df1.drop(['IsGifted', 'DSEN_Provision_Code'], axis = 1)
df2

Full_Name  organisation_key  person_learner_key  gender_key  \
0         Aadam Ali                 2                2531           1   
1         Aadam Ali                 2                2531           1   
2         Aadam Ali                 2                2531           1   
3         Aadam Ali                 2                2531           1   
4         Aadam Ali                 2                2531           1   
...             ...               ...                 ...         ...   
10603  Zoya Hussain                 1                1246           2   
10604   Zoya Rahman                 4                4469           2   
10605   Zoya Rahman                 4                4469           2   
10606   Zoya Waseem                 5                4482           2   
10607   Zoya Waseem                 5                4482           2   

       Present Gender_Code Student_Status  Behaviour_Points IsBankHoliday  \
0            0           M        On Roll               0.0             Y   
1            0           M        On Roll               0.0             Y   
2            1           M        On Roll               1.0             N   
3            0           M        On Roll               1.0             N   
4            1           M        On Roll               2.0             N   
...        ...         ...            ...               ...           ...   
10603        1           F        On Roll               NaN             N   
10604        0           F        On Roll               1.0             Y   
10605        1           F        On Roll               1.0             N   
10606        1           F        On Roll               NaN             N   
10607        0           F        On Roll               NaN             N   

      IsCompanyHoliday IsFederalHoliday IsLastDayOfMonth IsWeekday IsWeekend  \
0                    Y                Y                N         Y         N   
1                    Y                Y                Y         Y         N   
2                    N                N                N         Y         N   
3                    N                N                Y         Y         N   
4                    N                N                N         Y         N   
...                ...              ...              ...       ...       ...   
10603                N                N                Y         N         Y   
10604                Y                Y                N         Y         N   
10605                N                N                Y         Y         N   
10606                N                N                N         Y         N   
10607                N                N                Y         Y         N   

      IsWorkday  MonthNumberOfYear  
0             N                  7  
1             N                  7  
2             Y                  7  
3             Y                  7  
4             Y                  7  
...         ...                ...  
10603         N                  7  
10604         N                  7  
10605         Y                  7  
10606         Y                  7  
10607         Y                  7  

[10608 rows x 16 columns]

In [11]:
df2.columns

Index(['Full_Name', 'organisation_key', 'person_learner_key', 'gender_key',
       'Present', 'Gender_Code', 'Student_Status', 'Behaviour_Points',
       'IsBankHoliday', 'IsCompanyHoliday', 'IsFederalHoliday',
       'IsLastDayOfMonth', 'IsWeekday', 'IsWeekend', 'IsWorkday',
       'MonthNumberOfYear'],
      dtype='object')

In [12]:
df2.organisation_key.unique()

array([2, 1, 4, 5, 6, 3], dtype=int64)

In [13]:
df2.gender_key.unique()

array([1, 2], dtype=int64)

In [14]:
df2.Present.unique()

array([0, 1], dtype=int64)

In [15]:
df2.Gender_Code.unique()

array(['M', 'F'], dtype=object)

In [16]:
df2.Gender_Code = df2.Gender_Code.apply(lambda x : 1 if x == 'M' else 0) 
df2.Gender_Code.unique()

array([1, 0], dtype=int64)

In [17]:
df2.Student_Status.value_counts()

On Roll    9393
Leaver     1214
1             1
Name: Student_Status, dtype: int64

In [18]:
df2.Student_Status = df2.Student_Status.apply(lambda x : 1 if x == 'On Roll' else 0)

In [19]:
df2.Student_Status.unique()

array([1, 0], dtype=int64)

In [20]:
df2.Behaviour_Points.unique()

array([ 0.,  1.,  2.,  3.,  4.,  6., nan, 10.,  5.,  8.])

In [21]:
df2.Behaviour_Points.value_counts(normalize = 'True')

1.0     0.356854
0.0     0.267324
2.0     0.160597
3.0     0.108498
4.0     0.100910
5.0     0.003794
6.0     0.000759
10.0    0.000759
8.0     0.000506
Name: Behaviour_Points, dtype: float64

In [22]:
df2.IsBankHoliday.unique()

array(['Y', 'N'], dtype=object)

In [23]:
df2.IsBankHoliday = df2.IsBankHoliday.apply(lambda x : 1 if x == 'Y' else 0)

In [24]:
df2.IsBankHoliday.unique()

array([1, 0], dtype=int64)

In [25]:
df2.IsCompanyHoliday.unique()

array(['Y', 'N'], dtype=object)

In [26]:
df2.IsCompanyHoliday = df2.IsCompanyHoliday.apply(lambda x : 1 if x == 'Y' else 0)

In [27]:
df2.IsCompanyHoliday.unique()

array([1, 0], dtype=int64)

In [28]:
df2.IsBankHoliday = df2.IsBankHoliday.apply(lambda x : 1 if x == 'Y' else 0)

In [29]:
df2.IsFederalHoliday.unique()

array(['Y', 'N'], dtype=object)

In [30]:
df2.IsFederalHoliday = df2.IsFederalHoliday.apply(lambda x : 1 if x == 'Y' else 0)

In [31]:
df2.IsFederalHoliday.unique()

array([1, 0], dtype=int64)

In [32]:
df2.IsLastDayOfMonth.unique()

array(['N', 'Y'], dtype=object)

In [33]:
df2.IsLastDayOfMonth = df2.IsLastDayOfMonth.apply(lambda x : 1 if x == 'Y' else 0)

In [34]:
df2.IsLastDayOfMonth.unique()

array([0, 1], dtype=int64)

In [35]:
df2.IsWeekday.unique()

array(['Y', 'N', ' N'], dtype=object)

In [36]:
df2.IsWeekday = df2.IsWeekday.apply(lambda x : 1 if x == 'Y' else 0)

In [37]:
df2.IsWeekday.unique()

array([1, 0], dtype=int64)

In [38]:
df2.IsWeekend.unique()

array(['N', 'Y'], dtype=object)

In [39]:
df2.IsWeekend = df2.IsWeekend.apply(lambda x : 1 if x == 'Y' else 0)

In [40]:
df2.IsWeekend.unique()

array([0, 1], dtype=int64)

In [41]:
df2.IsWorkday.unique()

array(['N', 'Y'], dtype=object)

In [42]:
df2.IsWorkday = df2.IsWorkday.apply(lambda x : 1 if x == 'Y' else 0)

In [43]:
df2.IsWorkday.unique()

array([0, 1], dtype=int64)

In [44]:
df2.MonthNumberOfYear.unique()

array([7], dtype=int64)

In [45]:
df3 = df2.drop(['MonthNumberOfYear'], axis = 1) # dropping this column, as its having only single value 7
df3

Full_Name  organisation_key  person_learner_key  gender_key  \
0         Aadam Ali                 2                2531           1   
1         Aadam Ali                 2                2531           1   
2         Aadam Ali                 2                2531           1   
3         Aadam Ali                 2                2531           1   
4         Aadam Ali                 2                2531           1   
...             ...               ...                 ...         ...   
10603  Zoya Hussain                 1                1246           2   
10604   Zoya Rahman                 4                4469           2   
10605   Zoya Rahman                 4                4469           2   
10606   Zoya Waseem                 5                4482           2   
10607   Zoya Waseem                 5                4482           2   

       Present  Gender_Code  Student_Status  Behaviour_Points  IsBankHoliday  \
0            0            1               1               0.0              0   
1            0            1               1               0.0              0   
2            1            1               1               1.0              0   
3            0            1               1               1.0              0   
4            1            1               1               2.0              0   
...        ...          ...             ...               ...            ...   
10603        1            0               1               NaN              0   
10604        0            0               1               1.0              0   
10605        1            0               1               1.0              0   
10606        1            0               1               NaN              0   
10607        0            0               1               NaN              0   

       IsCompanyHoliday  IsFederalHoliday  IsLastDayOfMonth  IsWeekday  \
0                     1                 1                 0          1   
1                     1                 1                 1          1   
2                     0                 0                 0          1   
3                     0                 0                 1          1   
4                     0                 0                 0          1   
...                 ...               ...               ...        ...   
10603                 0                 0                 1          0   
10604                 1                 1                 0          1   
10605                 0                 0                 1          1   
10606                 0                 0                 0          1   
10607                 0                 0                 1          1   

       IsWeekend  IsWorkday  
0              0          0  
1              0          0  
2              0          1  
3              0          1  
4              0          1  
...          ...        ...  
10603          1          0  
10604          0          0  
10605          0          1  
10606          0          1  
10607          0          1  

[10608 rows x 15 columns]

In [46]:
df3.dtypes # All features are numerical except Full_Name column

Full_Name              object
organisation_key        int64
person_learner_key      int64
gender_key              int64
Present                 int64
Gender_Code             int64
Student_Status          int64
Behaviour_Points      float64
IsBankHoliday           int64
IsCompanyHoliday        int64
IsFederalHoliday        int64
IsLastDayOfMonth        int64
IsWeekday               int64
IsWeekend               int64
IsWorkday               int64
dtype: object

In [47]:
df2.isnull().sum()

Full_Name                0
organisation_key         0
person_learner_key       0
gender_key               0
Present                  0
Gender_Code              0
Student_Status           0
Behaviour_Points      2700
IsBankHoliday            0
IsCompanyHoliday         0
IsFederalHoliday         0
IsLastDayOfMonth         0
IsWeekday                0
IsWeekend                0
IsWorkday                0
MonthNumberOfYear        0
dtype: int64

In [48]:
np.mean(df3.Behaviour_Points)

1.4423368740515934

In [49]:
df3.Behaviour_Points.replace(to_replace = np.nan, value = 1.44, inplace=True) # NaN values replaced by mean value

In [50]:
df3.Behaviour_Points.unique()

array([ 0.  ,  1.  ,  2.  ,  3.  ,  4.  ,  6.  ,  1.44, 10.  ,  5.  ,
        8.  ])

In [51]:
df3.Behaviour_Points.value_counts()

1.00     2822
1.44     2700
0.00     2114
2.00     1270
3.00      858
4.00      798
5.00       30
6.00        6
10.00       6
8.00        4
Name: Behaviour_Points, dtype: int64

In [52]:
df3.isnull().sum() #No Null values are present

Full_Name             0
organisation_key      0
person_learner_key    0
gender_key            0
Present               0
Gender_Code           0
Student_Status        0
Behaviour_Points      0
IsBankHoliday         0
IsCompanyHoliday      0
IsFederalHoliday      0
IsLastDayOfMonth      0
IsWeekday             0
IsWeekend             0
IsWorkday             0
dtype: int64

In [53]:
df3.Full_Name.value_counts()

Usman Hussain          20
Haris Hussain          16
Marcel Lazok           12
Amaan Ahmed            12
Muhammad Ali           12
                       ..
Jaxon-Lee Broomhall     2
Jay Jeng                2
Jay Rutland             2
Jaya Bhatt              2
Zoya Waseem             2
Name: Full_Name, Length: 3228, dtype: int64

In [54]:
count = 0
for i in df3.Full_Name: 
        if i == i:
            df3.Full_Name.replace(to_replace = i, value = count, inplace=True)
            count+=1

In [55]:
df3.Full_Name.unique()

array([    9,    21,    23, ..., 10603, 10605, 10607], dtype=int64)

In [56]:
df3.describe()

Full_Name  organisation_key  person_learner_key    gender_key  \
count  10608.000000      10608.000000        10608.000000  10608.000000   
mean    5305.464932          2.681938         2605.127262      1.421003   
std     3062.501165          1.128196         1314.865042      0.493743   
min        9.000000          1.000000          222.000000      1.000000   
25%     2654.000000          2.000000         1548.750000      1.000000   
50%     5305.000000          2.000000         2577.000000      1.000000   
75%     7955.500000          3.000000         3795.000000      2.000000   
max    10607.000000          6.000000         8567.000000      2.000000   

            Present   Gender_Code  Student_Status  Behaviour_Points  \
count  10608.000000  10608.000000    10608.000000      10608.000000   
mean       0.970683      0.578997        0.885464          1.441742   
std        0.168703      0.493743        0.318476          1.139084   
min        0.000000      0.000000        0.000000          0.000000   
25%        1.000000      0.000000        1.000000          1.000000   
50%        1.000000      1.000000        1.000000          1.440000   
75%        1.000000      1.000000        1.000000          2.000000   
max        1.000000      1.000000        1.000000         10.000000   

       IsBankHoliday  IsCompanyHoliday  IsFederalHoliday  IsLastDayOfMonth  \
count        10608.0      10608.000000      10608.000000      10608.000000   
mean             0.0          0.003865          0.003865          0.500000   
std              0.0          0.062052          0.062052          0.500024   
min              0.0          0.000000          0.000000          0.000000   
25%              0.0          0.000000          0.000000          0.000000   
50%              0.0          0.000000          0.000000          0.500000   
75%              0.0          0.000000          0.000000          1.000000   
max              0.0          1.000000          1.000000          1.000000   

          IsWeekday     IsWeekend     IsWorkday  
count  10608.000000  10608.000000  10608.000000  
mean       0.940140      0.059860      0.936557  
std        0.237239      0.237239      0.243769  
min        0.000000      0.000000      0.000000  
25%        1.000000      0.000000      1.000000  
50%        1.000000      0.000000      1.000000  
75%        1.000000      0.000000      1.000000  
max        1.000000      1.000000      1.000000

In [57]:
df3.columns

Index(['Full_Name', 'organisation_key', 'person_learner_key', 'gender_key',
       'Present', 'Gender_Code', 'Student_Status', 'Behaviour_Points',
       'IsBankHoliday', 'IsCompanyHoliday', 'IsFederalHoliday',
       'IsLastDayOfMonth', 'IsWeekday', 'IsWeekend', 'IsWorkday'],
      dtype='object')

In [58]:
y = df3.Present
y.head

<bound method NDFrame.head of 0        0
1        0
2        1
3        0
4        1
        ..
10603    1
10604    0
10605    1
10606    1
10607    0
Name: Present, Length: 10608, dtype: int64>

In [59]:
X = df3.drop(['Present'], axis = 1)
X

Full_Name  organisation_key  person_learner_key  gender_key  \
0              9                 2                2531           1   
1              9                 2                2531           1   
2              9                 2                2531           1   
3              9                 2                2531           1   
4              9                 2                2531           1   
...          ...               ...                 ...         ...   
10603      10603                 1                1246           2   
10604      10605                 4                4469           2   
10605      10605                 4                4469           2   
10606      10607                 5                4482           2   
10607      10607                 5                4482           2   

       Gender_Code  Student_Status  Behaviour_Points  IsBankHoliday  \
0                1               1              0.00              0   
1                1               1              0.00              0   
2                1               1              1.00              0   
3                1               1              1.00              0   
4                1               1              2.00              0   
...            ...             ...               ...            ...   
10603            0               1              1.44              0   
10604            0               1              1.00              0   
10605            0               1              1.00              0   
10606            0               1              1.44              0   
10607            0               1              1.44              0   

       IsCompanyHoliday  IsFederalHoliday  IsLastDayOfMonth  IsWeekday  \
0                     1                 1                 0          1   
1                     1                 1                 1          1   
2                     0                 0                 0          1   
3                     0                 0                 1          1   
4                     0                 0                 0          1   
...                 ...               ...               ...        ...   
10603                 0                 0                 1          0   
10604                 1                 1                 0          1   
10605                 0                 0                 1          1   
10606                 0                 0                 0          1   
10607                 0                 0                 1          1   

       IsWeekend  IsWorkday  
0              0          0  
1              0          0  
2              0          1  
3              0          1  
4              0          1  
...          ...        ...  
10603          1          0  
10604          0          0  
10605          0          1  
10606          0          1  
10607          0          1  

[10608 rows x 14 columns]

In [60]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [61]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((8486, 14), (2122, 14), (8486,), (2122,))

In [62]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()
lr.fit(X_train, y_train)
lr.score(X_test, y_test)

C:\Users\Vaishu\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9684260131950989

In [63]:
from sklearn.tree import DecisionTreeClassifier
dtree = DecisionTreeClassifier(random_state = 0, max_depth=4)
dtree.fit(X_train, y_train)
y_pred_dt = dtree.predict(X_test)
print(dtree.score(X_test, y_test))
acc_score = accuracy_score(y_test, y_pred_dt)
print(acc_score)

0.971253534401508
0.971253534401508


In [64]:
from sklearn.tree import DecisionTreeClassifier
dt_ent = DecisionTreeClassifier(max_depth=6,criterion='entropy')
dt_ent.fit(X_train,y_train)
dt_ent.score(X_test, y_test)

0.972196041470311

In [66]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier()
rf.fit(X_train, y_train)
rf.score(X_test, y_test)

0.969368520263902

In [ ]:
# Decision Tree gives the highest accuracy.